name: Master - Build, Test, Pack & Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Clean
      run: dotnet clean ./WebEnv.Util.Mailer.sln -- configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Configure SMTP Settings
      uses: microsoft/variable-substitution@v1 
      with:
        files: './WebEnv.Util.Mailer.Tests/SmtpSettings.json'
      env:
        SmtpSettings.emailSmtpPassword: ${{ secrets.SMTP_PASSWORD }}
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Publish Coverage
      uses: codacy/codacy-coverage-reporter-action@0.2.0
      with:
        project-token: ${{ secrets.CODACY_TOKEN }}
        coverage-reports: WebEnv.Util.Mailer.Tests/coverage.opencover.xml
    - name: Build (Release)
      run: dotnet build -c Release --no-restore
    - name: Pack
      run: nuget pack ./WebEnv.Util.Mailer/.nuspec -OutputDirectory ./dist/ -Prop Configuration=Release -Suffix CI-${GITHUB_RUN_NUMBER}
    - name: Publish
      run: dotnet nuget push ./dist/*nupkg -s https://nuget.pkg.github.com/Web-Env/index.json --api-key="${{ secrets.GPR_TOKEN }}"
